from datetime import datetime
from typing import Optional, Dict, Any, List
import logging
from src.asta_brain.infrastructure.adapters.db.models import AuditLog
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger(__name__)

class AuditTrailService:
    def __init__(self, db_session_factory):
        self.db_session_factory = db_session_factory

    async def log_event(
        self, 
        session: AsyncSession,
        level: str, 
        module: str, 
        message: str, 
        metadata: Optional[Dict[str, Any]] = None
    ):
        """
        Persists a system event or decision to the audit log.
        """
        try:
            audit_entry = AuditLog(
                level=level,
                module=module,
                message=message,
                metadata_json=metadata,
                timestamp=datetime.utcnow()
            )
            session.add(audit_entry)
            await session.flush() # Ensure it's part of the transaction
            logger.info(f"AuditLog [{level}] [{module}]: {message}")
        except Exception as e:
            logger.error(f"Failed to write to AuditLog: {e}")

    async def get_recent_logs(self, session: AsyncSession, limit: int = 100) -> List[Dict[str, Any]]:
        """
        Retrieves the most recent audit logs.
        """
        from sqlalchemy import select
        stmt = select(AuditLog).order_by(AuditLog.timestamp.desc()).limit(limit)
        result = await session.execute(stmt)
        logs = result.scalars().all()
        
        return [
            {
                "id": log.id,
                "timestamp": log.timestamp.isoformat(),
                "level": log.level,
                "module": log.module,
                "message": log.message,
                "metadata": log.metadata_json
            }
            for log in logs
        ]

    async def log_trade_execution(self, session: AsyncSession, trade_id: str, details: Dict[str, Any]):
        await self.log_event(
            session,
            level="INFO",
            module="EXECUTION",
            message=f"Trade executed: {trade_id}",
            metadata=details
        )

    async def log_strategy_signal(self, session: AsyncSession, strategy_id: str, signal_details: Dict[str, Any]):
        await self.log_event(
            session,
            level="INFO",
            module="STRATEGY",
            message=f"Signal generated by {strategy_id}",
            metadata=signal_details
        )

    async def log_risk_rejection(self, session: AsyncSession, reason: str, request_details: Dict[str, Any]):
        await self.log_event(
            session,
            level="WARNING",
            module="RISK",
            message=f"Trade rejected by Risk Manager: {reason}",
            metadata=request_details
        )
